### ISSUE TITLE
Use second AMBA interconnect

### ISSUE THREAD

**Issue by ntimeu** [szanni/aeshw#1]
Hi,

I noticed your project on your blog and after working on it I noticed that you used the first AMBA interconnect to build your crypto core. This bus is used by all others peripherals so the crypto core could be slower.

I noticed in the Zybo [reference doc ](http://www.digilentinc.com/Data/Products/ZYBO/ZYBO_RM_B_V6.pdf) that there is a second AMBA interconnect available with AXI high performance ports (Cf page 5 on 26). I looked at the dts file where bus and peripherals are set but there is nothing about this second interconnect (which could be faster and less used).

Do you know if there is a way to use it ? Could it improve the crypto core performances ?

**Comment by szanni** [comment]
I'm sorry to only reply now but I think we are all currently busy hacking away on other projects :(
Regarding a second AMBA interconnect: do you mean the figure? I don't think that that implies a second interconnect. There are however different interconnect configurations.

In my opinion the only _correct_ way to increase performance would be to use the AXI scatter/gather engine and wire that up to the kernel driver. But docs on how to actually interact with the DMA engine from the software side seem to be nonexistent.
